### ISSUE TITLE
Clear internal hierarchy->node cache on solution close

### ISSUE THREAD

**Issue by kzu** [clariuslabs/clide#17] opened 2013-12-06 14:44 UTC
Currently we cache the managed nodes we create from the hierarchy, but we're not clearing that cache when the solution is closed. This is not serious since it would require long-running VS instances that open/close many solutions over time, which is not very typical VS usage.

But still, it should be done.

**Comment by GearedToWar** [comment] 2015-12-11 20:44
Yes, please consider fixing this.
I see the same problem when projects are loaded/unloaded. The cache keeps the hierarchies alive, thus leaking whole projects.

**Comment by AArnott** [comment] 2015-12-11 21:31
+1. Leaking whole projects / solutions can take hundreds of megabytes when the project or solution is large. 
Also, and perhaps more importantly, many hierarchy/node objects and most ItemIDs you get from enumerating the hierarchy are not guaranteed to be valid after you release the UI thread to let other code execute. *very* conscientious event handlers can inform you of when they are invalidated but I've never seen code written that did it properly. So the safest bet is to only hold itemIDs in local variables and if you must cache something, cache the result of calling GetMkDocument or GetCanonicalName. Then use the complementary methods to reverse it back into an ItemID when you come back to the UI thread later.

**Comment by kzu** [comment] 2015-12-16 15:39
[This is actually all we cache](https://github.com/clariuslabs/clide/blob/master/src/Clide/Solution/Implementation/AggregateHierarchyFactory.cs#L50): a tuple of two ints and their associated factory (which is a singleton too). 

As far as changing ItemIDs, that would just cause a miss on the lookup of the associated factory, and nothing more. We'd always construct the adapter interface on top of the right hierarchy item anyway. Granted, if those change a lot, then we would leak a tuple for each changed id :(.

Moving forward, we're changing the implementation entirely to be based on the new (VS2012+) IVsHierarchyItemManager, which allows us to do away with all this caching stuff entirely.

/cc @victorgarciaaprea

**Comment by GearedToWar** [comment] 2015-12-17 00:20
That is not what we are seeing.

The leaks mostly originate from SolutionExplorerNodeFactory](https://github.com/clariuslabs/clide/blob/master/src/Clide/Solution/Implementation/SolutionExplorerNodeFactory.cs), specifically the nodeCache dictionary which keeps references to hierarchies.

As a final test, I deleted the Xamarin extension from the machine and reran the tests - all the leaks went away.

I'll be happy to provide more details and/or verify any changes you make to fix this.

**Comment by AArnott** [comment] 2015-12-17 15:37
@GearedToWar Do you have a `!gcroot` you could share?

**Comment by GearedToWar** [comment] 2015-12-18 18:42
Here's one that I stored from a memory leak tool I was using. @kzu let me know if you need more data from my investigation.

Children of "<-System.Tuple`2<Microsoft.VisualStudio.Shell.Interop.IVsHierarchy,System.UInt32>.m_Item1 0x1721f684 (16)"
<-System.Tuple`2<Microsoft.VisualStudio.Shell.Interop.IVsHierarchy,System.UInt32>.m_Item1 0x1721f684 (16)
 <-System.Collections.Concurrent.ConcurrentDictionary`2<System.Tuple`2<Microsoft.VisualStudio.Shell.Interop.IVsHierarchy,System.UInt32>,Clide.Solution.ISolutionExplorerNode>.Node<System.Tuple`2<Microsoft.VisualStudio.Shell.Interop.IVsHierarchy,System.UInt32>,Clide.Solution.ISolutionExplorerNode>.m_key 0x172f9a08 (24)
  <-System.Collections.Concurrent.ConcurrentDictionary`2<System.Tuple`2<Microsoft.VisualStudio.Shell.Interop.IVsHierarchy,System.UInt32>,Clide.Solution.ISolutionExplorerNode>+System.Collections.Concurrent.ConcurrentDictionary`2<System.Tuple`2<Microsoft.VisualStudio.Shell.Interop.IVsHierarchy,System.UInt32>,Clide.Solution.ISolutionExplorerNode>.Node<System.Tuple`2<Microsoft.VisualStudio.Shell.Interop.IVsHierarchy,System.UInt32>,Clide.Solution.ISolutionExplorerNode>[](Count=67) 0x172f9804 (280)
   <-System.Collections.Concurrent.ConcurrentDictionary`2<System.Tuple`2<Microsoft.VisualStudio.Shell.Interop.IVsHierarchy,System.UInt32>,Clide.Solution.ISolutionExplorerNode>.Tables<System.Tuple`2<Microsoft.VisualStudio.Shell.Interop.IVsHierarchy,System.UInt32>,Clide.Solution.ISolutionExplorerNode>(Count=17).m_buckets 0x172f9a98 (24)
    <-System.Collections.Concurrent.ConcurrentDictionary`2<System.Tuple`2<Microsoft.VisualStudio.Shell.Interop.IVsHierarchy,System.UInt32>,Clide.Solution.ISolutionExplorerNode>(Count=17).m_tables 0x0360b1a4 (40)
     <-Clide.Solution.Implementation.SolutionExplorerNodeFactory.nodeCache 0x0360b194 (16)

**Comment by AArnott** [comment] 2015-12-18 20:16
@GearedToWar You may want to surround your pasted bit with three back-tick characters so that markdown doesn't try to format it.

**Comment by kzu** [comment] 2015-12-18 21:33
@GearedToWar that cache is cleared on [every solution closed event](https://github.com/clariuslabs/clide/blob/master/src/Clide/Solution/Implementation/SolutionExplorerNodeFactory.cs#L36)

**Comment by GearedToWar** [comment] 2015-12-18 21:37
That does not cover the scenario where projects are added/removed or are unloaded/reloaded in the solution.

**Comment by kzu** [comment] 2015-12-18 22:06
Yup, but aside from some continuous integration testing scenarios, that
covers the vast majority of normal VS usage cases, I think

**Comment by GearedToWar** [comment] 2015-12-18 22:19
We have tests to explicitly cover these scenarios. Since this is a significant regression, I think it should be fixed.
The larger issue is that with such big leaks in the scenario, it is practically impossible to maintain a quality bar.
With this regression in, it is not possible to monitor the data on a regular basis and point to new leaks. The leak values have increased from ~10KB to ~1MB. Compared to the new value, any new leak would look like noise and pretty soon we will have several additional leaks with no accountability. Fixing issues is another challenge - any investigation would have to ignore all leaks originating from this code.

So, please consider fixing this.

**Comment by AArnott** [comment] 2015-12-18 22:33
To fill in a little of why we care so much, @kzu, your library is for most practical purposes part of VS now. Xamarin installs with many VS installations and Xamarin brings in your library. Since we test VS in the configurations found by most of our customers, that means your library is involved in our testing.

On one hand, that's good for you because you'll get more testing of your library for free. :)
On the other, it means we'll occasionally ask you to fix bugs to keep our tests running smoothly.

**Comment by kzu** [comment] 2015-12-18 23:24
Fair enough. Will most likely kill the caching altogether then ;)

**Comment by GearedToWar** [comment] 2015-12-19 01:34
Great. Thank you.

**Closed** 2015-12-21 15:31 UTC
Labels: 0 - Backlog

**Comment by AArnott** [comment] 2015-12-21 15:37
Thanks!

**Comment by kzu** [comment] 2015-12-21 15:48
No problem! Should be included in our next major release, unless this is
critical enough for you to deserve inclusion in an earlier release. If
that's the case, could you please report it via bugzilla.xamarin.com so I
can make the case to ship it earlier?

Thanks!

**Comment by GearedToWar** [comment] 2015-12-21 22:15
When is the next major release planned?

**Comment by kzu** [comment] 2015-12-21 22:43
Alpha sometime in January, I think

**Comment by GearedToWar** [comment] 2015-12-22 00:35
That works for us. Thanks.

**Comment by kzu** [comment] 2015-12-22 03:32
Cool :)
